apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: spring-sensors-rabbit-prod
  labels:
    app.kubernetes.io/part-of: spring-sensors-rabbit
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    management.endpoint.health.show-details: always
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.actuator.port: "8081"
    tanzu.app.live.view.application.name: spring-sensors-rabbit-prod
    tanzu.app.live.view.application.port: "8080"
    app.kubernetes.io/component: run
    carto.run/workload-name: spring-sensors-rabbit-prod
spec:
  template:
    metadata:
      annotations:
        boot.spring.io/actuator: http://:8081/actuator
        boot.spring.io/version: 2.5.8
        conventions.apps.tanzu.vmware.com/applied-conventions: |-
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          spring-boot-convention/spring-boot-actuator
          spring-boot-convention/service-intent-mysql
          spring-boot-convention/service-intent-rabbitmq
        developer.conventions/target-containers: workload
        services.conventions.apps.tanzu.vmware.com/mysql: mysql-connector-java/8.0.27
        services.conventions.apps.tanzu.vmware.com/rabbitmq: amqp-client/5.12.0
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: spring-sensors-rabbit
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: spring-sensors-rabbit-prod
        conventions.apps.tanzu.vmware.com/framework: spring-boot
        management.endpoint.health.show-details: always
        services.conventions.apps.tanzu.vmware.com/mysql: workload
        services.conventions.apps.tanzu.vmware.com/rabbitmq: workload
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.actuator.port: "8081"
        tanzu.app.live.view.application.name: spring-sensors-rabbit-prod
        tanzu.app.live.view.application.port: "8080"
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.endpoints.web.base-path="/actuator" -Dmanagement.health.probes.enabled="true" -Dmanagement.server.port="8081" -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: registry.harbor.t3u.link/tap-project/supply-chain/spring-sensors-rabbit-prod-default@sha256:04b60991baec8b71536f0e9ca6ec016b7232d2b64bd3dd3ce778a24466052de8
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

